-- MySQL Script generated by MySQL Workbench
-- Wed Jun 28 15:01:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `logradouro` VARCHAR(80) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Animal` (
  `id_an` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `data_nasc` DATE NULL,
  `Cliente_idCliente` INT NOT NULL,
  `pelagem` CHAR(1) NULL,
  `porte` CHAR(1) NULL,
  `agressivo` TINYINT NULL,
  `obs` VARCHAR(100) NULL,
  PRIMARY KEY (`id_an`, `Cliente_idCliente`),
  INDEX `fk_Animal_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_us` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(80) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_us`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Servico` (
  `id_os` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(10) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `valorTotal` FLOAT NOT NULL,
  `data_in` DATE NULL,
  `Usuario_id_us` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Animal_id_an` INT NOT NULL,
  `Animal_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`id_os`, `Animal_id_an`, `Animal_Cliente_idCliente`),
  INDEX `fk_Servicos_Usuario_idx` (`Usuario_id_us` ASC) VISIBLE,
  INDEX `fk_Servicos_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Servicos_Animal1_idx` (`Animal_id_an` ASC, `Animal_Cliente_idCliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servico` (
  `id_ser` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(10) NULL,
  `valor` FLOAT NULL,
  PRIMARY KEY (`id_ser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemOS` (
  `id_ItemOS` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NULL,
  `OS_id_os` INT NOT NULL,
  `servico_id_ser` INT NOT NULL,
  PRIMARY KEY (`id_ItemOS`, `OS_id_os`),
  INDEX `fk_ItemOS_OS1_idx` (`OS_id_os` ASC) VISIBLE,
  INDEX `fk_ItemOS_servico1_idx` (`servico_id_ser` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
