"""Adicionando campos porte, agressivo, obs, pelagem

Revision ID: f86670f0939b
Revises: 
Create Date: 2023-11-23 08:21:40.733143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f86670f0939b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('pelagem',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('porte',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=3),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('porte',
               existing_type=sa.String(length=3),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('pelagem',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
